import type { CompetitorSong } from '../types/gameTypes';

export const DEFAULT_CHART_COMPETITORS: CompetitorSong[] = [
  // Pop/Mainstream (25 songs) - High streams 800K-1M
  { id: 'comp_001', title: 'Electric Dreams', artist: 'Luna Rose', baseStreams: 950000, genre: 'pop' },
  { id: 'comp_002', title: 'Midnight City', artist: 'The Neon Lights', baseStreams: 920000, genre: 'pop' },
  { id: 'comp_003', title: 'Golden Hour', artist: 'Skylar Blue', baseStreams: 890000, genre: 'pop' },
  { id: 'comp_004', title: 'Dancing Shadows', artist: 'Crystal Dreams', baseStreams: 875000, genre: 'pop' },
  { id: 'comp_005', title: 'Fire in the Rain', artist: 'Phoenix Rising', baseStreams: 860000, genre: 'pop' },
  { id: 'comp_006', title: 'Starlight Boulevard', artist: 'Madison Vale', baseStreams: 845000, genre: 'pop' },
  { id: 'comp_007', title: 'Ocean Waves', artist: 'Coral Reef', baseStreams: 830000, genre: 'pop' },
  { id: 'comp_008', title: 'Neon Nights', artist: 'Electric Youth', baseStreams: 815000, genre: 'pop' },
  { id: 'comp_009', title: 'Sugar Rush', artist: 'Candy Hearts', baseStreams: 800000, genre: 'pop' },
  { id: 'comp_010', title: 'Velvet Sky', artist: 'Dream State', baseStreams: 885000, genre: 'pop' },
  { id: 'comp_011', title: 'Paper Planes', artist: 'Summer Storm', baseStreams: 870000, genre: 'pop' },
  { id: 'comp_012', title: 'Mirror Ball', artist: 'Disco Fever', baseStreams: 855000, genre: 'pop' },
  { id: 'comp_013', title: 'Wild Hearts', artist: 'Freedom Call', baseStreams: 840000, genre: 'pop' },
  { id: 'comp_014', title: 'Silver Lining', artist: 'Cloud Nine', baseStreams: 825000, genre: 'pop' },
  { id: 'comp_015', title: 'Diamond Eyes', artist: 'Precious Stone', baseStreams: 810000, genre: 'pop' },
  { id: 'comp_016', title: 'Thunder Storm', artist: 'Lightning Bolt', baseStreams: 895000, genre: 'pop' },
  { id: 'comp_017', title: 'Cosmic Love', artist: 'Galaxy Girl', baseStreams: 880000, genre: 'pop' },
  { id: 'comp_018', title: 'Sunset Drive', artist: 'Highway Dreams', baseStreams: 865000, genre: 'pop' },
  { id: 'comp_019', title: 'Purple Rain', artist: 'Violet Storm', baseStreams: 850000, genre: 'pop' },
  { id: 'comp_020', title: 'Angel Wings', artist: 'Heaven Sent', baseStreams: 835000, genre: 'pop' },
  { id: 'comp_021', title: 'Magic Moment', artist: 'Fairy Tale', baseStreams: 820000, genre: 'pop' },
  { id: 'comp_022', title: 'Shooting Star', artist: 'Meteor Shower', baseStreams: 905000, genre: 'pop' },
  { id: 'comp_023', title: 'Butterfly Effect', artist: 'Metamorphosis', baseStreams: 890000, genre: 'pop' },
  { id: 'comp_024', title: 'Crystal Clear', artist: 'Pure Light', baseStreams: 875000, genre: 'pop' },
  { id: 'comp_025', title: 'Endless Summer', artist: 'Beach Vibes', baseStreams: 860000, genre: 'pop' },

  // Hip-Hop/R&B (20 songs) - Medium-high streams 600K-800K
  { id: 'comp_026', title: 'City Streets', artist: 'Urban Legend', baseStreams: 750000, genre: 'hip-hop' },
  { id: 'comp_027', title: 'Gold Chains', artist: 'Money Mike', baseStreams: 720000, genre: 'hip-hop' },
  { id: 'comp_028', title: 'Midnight Hustle', artist: 'Street King', baseStreams: 690000, genre: 'hip-hop' },
  { id: 'comp_029', title: 'Diamond Grillz', artist: 'Ice Cold', baseStreams: 675000, genre: 'hip-hop' },
  { id: 'comp_030', title: 'Smooth Operator', artist: 'Silky Voice', baseStreams: 730000, genre: 'r&b' },
  { id: 'comp_031', title: 'Love Letters', artist: 'Soul Sister', baseStreams: 710000, genre: 'r&b' },
  { id: 'comp_032', title: 'Velvet Touch', artist: 'Smooth Moves', baseStreams: 685000, genre: 'r&b' },
  { id: 'comp_033', title: 'Bass Drop', artist: 'Heavy Beats', baseStreams: 665000, genre: 'hip-hop' },
  { id: 'comp_034', title: 'Rhythm Nation', artist: 'Beat Master', baseStreams: 645000, genre: 'hip-hop' },
  { id: 'comp_035', title: 'Soulful Eyes', artist: 'Heart Strings', baseStreams: 740000, genre: 'r&b' },
  { id: 'comp_036', title: 'Street Dreams', artist: 'Rising Star', baseStreams: 700000, genre: 'hip-hop' },
  { id: 'comp_037', title: 'Honey Voice', artist: 'Sweet Melody', baseStreams: 680000, genre: 'r&b' },
  { id: 'comp_038', title: 'Crown King', artist: 'Royal Blood', baseStreams: 660000, genre: 'hip-hop' },
  { id: 'comp_039', title: 'Midnight Soul', artist: 'Dark Velvet', baseStreams: 725000, genre: 'r&b' },
  { id: 'comp_040', title: 'Urban Jungle', artist: 'Concrete King', baseStreams: 695000, genre: 'hip-hop' },
  { id: 'comp_041', title: 'Liquid Gold', artist: 'Golden Voice', baseStreams: 715000, genre: 'r&b' },
  { id: 'comp_042', title: 'Fast Lane', artist: 'Speed Demon', baseStreams: 670000, genre: 'hip-hop' },
  { id: 'comp_043', title: 'Silk Sheets', artist: 'Luxury Life', baseStreams: 650000, genre: 'r&b' },
  { id: 'comp_044', title: 'Money Trees', artist: 'Cash Flow', baseStreams: 635000, genre: 'hip-hop' },
  { id: 'comp_045', title: 'Sweet Dreams', artist: 'Lullaby Queen', baseStreams: 755000, genre: 'r&b' },

  // Rock/Alternative (18 songs) - Medium streams 400K-600K
  { id: 'comp_046', title: 'Breaking Chains', artist: 'Steel Heart', baseStreams: 580000, genre: 'rock' },
  { id: 'comp_047', title: 'Electric Storm', artist: 'Thunder Gods', baseStreams: 550000, genre: 'rock' },
  { id: 'comp_048', title: 'Rebel Yell', artist: 'Wild Ones', baseStreams: 520000, genre: 'rock' },
  { id: 'comp_049', title: 'Dark Side', artist: 'Shadow Band', baseStreams: 490000, genre: 'alternative' },
  { id: 'comp_050', title: 'Neon Lights', artist: 'City Nights', baseStreams: 460000, genre: 'alternative' },
  { id: 'comp_051', title: 'Fire Storm', artist: 'Flame Throwers', baseStreams: 430000, genre: 'rock' },
  { id: 'comp_052', title: 'Lost Highway', artist: 'Road Warriors', baseStreams: 570000, genre: 'rock' },
  { id: 'comp_053', title: 'Broken Dreams', artist: 'Shattered Glass', baseStreams: 540000, genre: 'alternative' },
  { id: 'comp_054', title: 'Iron Will', artist: 'Metal Hearts', baseStreams: 510000, genre: 'rock' },
  { id: 'comp_055', title: 'Silent Storm', artist: 'Quiet Riot', baseStreams: 480000, genre: 'alternative' },
  { id: 'comp_056', title: 'Phoenix Rising', artist: 'Ash to Fire', baseStreams: 450000, genre: 'rock' },
  { id: 'comp_057', title: 'Midnight Run', artist: 'Night Riders', baseStreams: 420000, genre: 'rock' },
  { id: 'comp_058', title: 'Wild Spirit', artist: 'Free Birds', baseStreams: 560000, genre: 'alternative' },
  { id: 'comp_059', title: 'Stone Cold', artist: 'Granite Kings', baseStreams: 530000, genre: 'rock' },
  { id: 'comp_060', title: 'Electric Dreams', artist: 'Voltage', baseStreams: 500000, genre: 'alternative' },
  { id: 'comp_061', title: 'Crimson Tide', artist: 'Red Wave', baseStreams: 470000, genre: 'rock' },
  { id: 'comp_062', title: 'Velvet Underground', artist: 'Smooth Rebels', baseStreams: 440000, genre: 'alternative' },
  { id: 'comp_063', title: 'Steel Magnolia', artist: 'Southern Storm', baseStreams: 410000, genre: 'rock' },

  // Electronic/Dance (15 songs) - Variable streams 300K-700K
  { id: 'comp_064', title: 'Bass Line', artist: 'DJ Electric', baseStreams: 680000, genre: 'electronic' },
  { id: 'comp_065', title: 'Pulse Beat', artist: 'Rhythm Machine', baseStreams: 620000, genre: 'electronic' },
  { id: 'comp_066', title: 'Neon Nights', artist: 'Laser Show', baseStreams: 580000, genre: 'electronic' },
  { id: 'comp_067', title: 'Digital Dreams', artist: 'Cyber Soul', baseStreams: 540000, genre: 'electronic' },
  { id: 'comp_068', title: 'Electric Feel', artist: 'Voltage Drop', baseStreams: 500000, genre: 'electronic' },
  { id: 'comp_069', title: 'Synthetic Love', artist: 'Robot Hearts', baseStreams: 460000, genre: 'electronic' },
  { id: 'comp_070', title: 'Frequency', artist: 'Sound Wave', baseStreams: 420000, genre: 'electronic' },
  { id: 'comp_071', title: 'Matrix Code', artist: 'Digital Underground', baseStreams: 380000, genre: 'electronic' },
  { id: 'comp_072', title: 'Laser Beam', artist: 'Light Speed', baseStreams: 340000, genre: 'electronic' },
  { id: 'comp_073', title: 'Circuit Board', artist: 'Tech Noir', baseStreams: 300000, genre: 'electronic' },
  { id: 'comp_074', title: 'Bass Drop', artist: 'Sub Sonic', baseStreams: 650000, genre: 'electronic' },
  { id: 'comp_075', title: 'Electro Shock', artist: 'High Voltage', baseStreams: 590000, genre: 'electronic' },
  { id: 'comp_076', title: 'Cyber Punk', artist: 'Future Funk', baseStreams: 550000, genre: 'electronic' },
  { id: 'comp_077', title: 'Digital Rain', artist: 'Code Matrix', baseStreams: 510000, genre: 'electronic' },
  { id: 'comp_078', title: 'Neon Flash', artist: 'Glow Stick', baseStreams: 470000, genre: 'electronic' },

  // Indie/Folk/Country (20 songs) - Lower streams 50K-400K
  { id: 'comp_079', title: 'Country Roads', artist: 'Hometown Hero', baseStreams: 380000, genre: 'country' },
  { id: 'comp_080', title: 'Whiskey Nights', artist: 'Bourbon Blues', baseStreams: 350000, genre: 'country' },
  { id: 'comp_081', title: 'Mountain High', artist: 'Alpine Dreams', baseStreams: 320000, genre: 'folk' },
  { id: 'comp_082', title: 'River Song', artist: 'Creek Bend', baseStreams: 290000, genre: 'folk' },
  { id: 'comp_083', title: 'Prairie Wind', artist: 'Open Sky', baseStreams: 260000, genre: 'country' },
  { id: 'comp_084', title: 'Coffee Shop', artist: 'Indie Dreams', baseStreams: 230000, genre: 'indie' },
  { id: 'comp_085', title: 'Vintage Love', artist: 'Retro Hearts', baseStreams: 200000, genre: 'indie' },
  { id: 'comp_086', title: 'Acoustic Soul', artist: 'String Theory', baseStreams: 170000, genre: 'folk' },
  { id: 'comp_087', title: 'Small Town', artist: 'Main Street', baseStreams: 140000, genre: 'country' },
  { id: 'comp_088', title: 'Moonlight Drive', artist: 'Backyard Band', baseStreams: 110000, genre: 'indie' },
  { id: 'comp_089', title: 'Campfire Song', artist: 'Woods Walker', baseStreams: 80000, genre: 'folk' },
  { id: 'comp_090', title: 'Dusty Roads', artist: 'Desert Rose', baseStreams: 50000, genre: 'country' },
  { id: 'comp_091', title: 'Garden Party', artist: 'Flower Power', baseStreams: 190000, genre: 'indie' },
  { id: 'comp_092', title: 'Sunset Porch', artist: 'Sweet Tea', baseStreams: 220000, genre: 'country' },
  { id: 'comp_093', title: 'Forest Path', artist: 'Nature Child', baseStreams: 160000, genre: 'folk' },
  { id: 'comp_094', title: 'Vinyl Records', artist: 'Thrift Store', baseStreams: 130000, genre: 'indie' },
  { id: 'comp_095', title: 'Barn Dance', artist: 'Hay Fever', baseStreams: 100000, genre: 'country' },
  { id: 'comp_096', title: 'Autumn Leaves', artist: 'Seasonal Change', baseStreams: 70000, genre: 'folk' },
  { id: 'comp_097', title: 'Typewriter', artist: 'Poetry Club', baseStreams: 60000, genre: 'indie' },
  { id: 'comp_098', title: 'Firefly Night', artist: 'Summer Memories', baseStreams: 90000, genre: 'folk' }
];
